### PR TITLE
Fix return type of `objectKeys()`

### LINKED ISSUE #13: Return type of `objectKeys()` omits the number type key
Return type of `objectKeys()` omits the number type key.

```ts
const items = objectKeys({1: 1, b: 2, c: 3});
// const items: ("b" | "c")[]

// expect
// const items: ("1" | "b" | "c")[]
```

### PR DESCRIPTION
**Pull request by jonahsnider**
Resolves #13 

Implements the same type logic as #12.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Tests are failing

File: test/object-keys.ts [hunk 1]
```diff
@@ -3,8 +3,8 @@ import {expectTypeOf} from 'expect-type';
 import {objectKeys} from '../source/index.js';
 
 test('objectKeys()', t => {
-	type Item = 'a' | 'b' | 'c';
-	const items = objectKeys({a: 1, b: 2, c: 3});
+	type Item = 'a' | 'b' | 'c' | '4';
+	const items = objectKeys({a: 1, b: 2, c: 3, 4: 4, [Symbol('5')]: 5});
 
 	expectTypeOf<Item[]>(items);
 	t.deepEqual(items, ['a', 'b', 'c']);
```
Comment (younho9) [inline test/object-keys.ts:10]:
```suggestion
	t.deepEqual(items, ['a', 'b', 'c', '4']);
```

add '4' to test case

**Comment by sindresorhus** [comment]
Can you add the type to the object entries type too?
